language: bash
sudo: false
os:
  - linux
  - osx

before_install:
  - '[[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update && brew install coreutils'

script:
  - bash run_tests.sh

notifications:
  email:
    recipients:
      - fabioroger@gmail.com
