language: bash
sudo: false
os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install coreutils; fi

script:
  - bash run_tests.sh

notifications:
  email:
    recipients:
      - fabioroger@gmail.com
