#!/usr/bin/env python

import sys
import os
import subprocess
import signal

# os.setpgrp()
p = subprocess.Popen(['bash', '-c', sys.argv[1]])
try:
	p.wait()
except KeyboardInterrupt:
	os.kill(p.pid, signal.SIGINT)
