#!/usr/bin/env python

from __future__ import print_function

try:
  from configparser import ConfigParser       # Python 3 import
except ImportError:
  from ConfigParser import ConfigParser   # If ConfigParser missing, we're on Py3, import Py2 as Py3 name

import os
import optparse
import sys

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def readConfigFrom(dir, config=ConfigParser.SafeConfigParser()):
	for root, subdirs, files in os.walk(dir):
		for file in files:
			eprint("Reading config from file %s" % os.path.join(root, file))
			config.read(os.path.join(root, file))
		for dir in subdirs:
			readConfigFrom(os.path.join(root, dir))

	return config


def main():
	parser = optparse.OptionParser(usage="Usage: %prog [options]", description=
		"Starts one forwarder for each configuration found in /etc/forwarder.d/ directory.")

	parser.add_option('-c', '--config', action="store", dest="config", help="Directory where to read the config files (default to /etc/forwarder.d).", default='/etc/forwarder.d')

	options, args = parser.parse_args()

	eprint("Config directory: %s" % options.config)
	config = readConfigFrom(options.config)

	eprint("")
	for section in config.sections():
		for option in config.options(section):
			value = config.get(section, option)
			print ("%s.%s = %s" % (section, option, value))


if __name__ == '__main__':
	main()
